# Generated by Django 4.2.3 on 2023-07-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_app', '0002_destination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
